### ISSUE TITLE
Feature: User can add Pokemon.

### ISSUE THREAD

**Issue by laykevin** [laykevin/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add (deposit) Pokemon to their collection (box).
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user types in a name of a Pokemon in the 'Add Pokemon' input, a request is made to PokeAPI to get data about that pokemon and stores the data to localStorage.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121647421/221702397-166f02e7-3ca5-4118-b5da-9cca926dcc10.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML and CSS for the header/nav bar to match the figma. 
  - [x] Create CSS for mobile first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Set background image.
- [x] Under the header/nav bar, create a centered heading titled 'Box 1' to match the figma.
- [x] Under the 'Box 1' heading, create form with a text input and a submit (deposit) button to match the figma.
- [x] In data.js:
  - [x] Create an object assigned to a variable.
  - [x] The object has a property 'view' with the value 'box-view'
  - [x] The object has a property 'entries' with the value of an empty array.
  - [x] The object has a property 'editing' with a value of null.
  - [x] The object has a property 'nextEntryId' with a value of 1.
- [x] Add a script tag at the bottom of the body, but above the main.js script tag with an src attribute with a value of data.js
- [x] Add a 'submit' event listener to the form button that:
  - [x] prevents the page from refreshing when the button is clicked.
  - [x] makes a request to the PokeAPI to get the data of the pokemon the user typed and store the data in a new object.
  - [x] assigns an entryId property to the new object, taken from the nextEntryId property of the data model.
  - [x] increments the nextEntryId property of the data model so that if another entry is submitted later, it will receive a different entryId.
  - [x] adds the new object to the beginning of the data model's array of entries.
  - [x] resets the form.
- [x] In data.js, add a 'beforeunload' event listener to the window object that serializes the data model as JSON and stores the JSON in localStorage.
- [x] At the bottom of data.js, include a conditional statement that:
  - [x] checks to see if there is a JSON data model stored in localStorage.
  - [x] if there is, parse it and assign it to the initial data variable so that the user can continue adding entries to the pre-existing data model.
- [x] Test the app by submitting some new entries and then reloading the page to confirm that:
  - [x] the data model is being saved to localStorage before each page reload.
  - [x] each new journal entry object is receiving an incrementing entryId property.
- [x] Add an error message if the user types in a Pokemon that doesn't exist.
- [x] Make sure that data is only stored and nextEntryId is only incremented for valid Pokemon.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
