### ISSUE TITLE
Feature: User can make their Pokemon shiny

### ISSUE THREAD

**Issue by laykevin** [laykevin/ajax-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can make their Pokemon shiny
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the shiny icon in the editing modal, the official artwork and the sprite of that Pokemon change to the shiny version.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121647421/222600673-fdc0e8ac-5427-488e-a23a-35cf4a68dc3a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a font awesome icon to the editing modal.
- [x] Add an event listener to the icon that does the following when clicked:
  - [x] Changes the official artwork to the shiny version if the current official artwork is the regular version.
  - [x] Changes the official artwork to the regular version if the current official artwork is the shiny version.
  - [x] Changes the sprite of the pokemon to the shiny version if the sprite is the regular version.
  - [x] Changes the sprite of the pokemon to the regular version if the sprite is the shiny version.
- [x] Only keep the changes when the user clicks the save button, but the user should be able to see the shiny version before saving if they click the icon.
