### ISSUE TITLE
Feature: User can view their Pokemon's types

### ISSUE THREAD

**Issue by laykevin** [laykevin/ajax-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their Pokemon's type.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user opens the editing modal, the user can see their Pokemon's types under the official artwork of the Pokemon. The types will be styled to resemble the game.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121647421/222835758-fa0dfba6-046b-47ac-b251-dc1d8bdf0f9b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create CSS for a span element to resemble the pokemon's type in the figma.
- [x] Create CSS for all pokemon type colors that will be used based on which types the specific pokemon has.
- [x] Create a new div with the id 'types-container' under the '.official-artwork' `img` element inside the modal part of the html.
- [x] Create a function that renders the Pokemon's type when the editing modal is opened to match the figma.
- [x] The function needs to:
  - [x] loop through types property stored in the pokemon's object (taken from the api) to get how many types and which types.
  - [x] create span elements for each type
  - [x] give those span elements the new CSS class you just made.
  - [x] give those span elements the correct CSS color classes you just made.
  - [x] append them to the new 'type-containers' div
  - [x] clear the children of the 'type-containers' div every time the editing modal is opened.
- [x] Call the function whenever the editing modal is opened.
