### ISSUE TITLE
Feature: User can view their Pokemon

### ISSUE THREAD

**Issue by laykevin** [laykevin/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view the Pokemon they added.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user opens the app, the sprites of all the Pokemon they entered from the past will show in the box-view. When the user adds another Pokemon, it will also show in the box view.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121647421/221958664-7f395e3d-1177-434f-a5b7-b242d62dd2f2.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div` element below the form to hold the sprites of the Pokemon
  - [x] Give the new div CSS properties of: `display: flex` and `flex-wrap: wrap`.
- [x] Add some dummy sprites to the `div` and adjust size to match figma (2 sprites for mobile view, 6 sprites for desktop view).
- [x] Define a `function` named `renderPokemon` with a single parameter named pokemon. This parameter represents a single object for a single entry from the `data.entries` array. The function should generate and return a DOM tree for a single entry that matches the entries you created in the new `div`.
- [x] Create an event listener on the document which listens for the `DOMContentLoaded` event. In the callback function for that event, loop through the `data.entries` array and generate a DOM tree for each entry in the array, and append that DOM tree to the new div.
- [x] Remove the example HTML sprites from index.html once the user's entries are successfully being appended to the DOM on page load.
- [x] Update the `submit` callback for the form to do the following:
  - [x] Render a DOM tree for new Pokemon submitted using the `renderPokemon` function.
  - [x] Prepends the new DOM tree to the new `div`.
- [x] Clean up all unnecessary styling.
- [x] Test the app some more in a private browsing tab.
- [x] Fix all errors.
