### ISSUE TITLE
Feature: User can edit a Pokemon

### ISSUE THREAD

**Issue by laykevin** [laykevin/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit a Pokemon.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on a sprite of a Pokemon, a modal will appear that lets them add other information about their Pokemon.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121647421/221999254-e08c80a7-d89f-45d3-bc85-2238ac0a412e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In HTML and CSS, create a modal that has a `form` that resembles the figma. 
  - [x] Give the modal a class of 'hidden' to hide it with the `display: none` CSS styling.
- [x] Update the renderPokemon function to add a 'data-entry-id' attribute to each sprite that stores the entryId of the pokemon being rendered.
- [x] Add an event listener to the box-sprites `div` that listens for 'click' on `img` elements.
  - [x] When a sprite (an `img` element) is clicked, remove the class of 'hidden' from the modal to display it.
  - [x] Find the entry object in the data.entries array whose id matches the data-entry-id attribute value of the clicked sprite and:
    - [x] Assigns that entry’s object to the data.editing property.
    - [x]  update the photo in the modal to the official artwork and display the name of the Pokemon from the data in data.editing.
    - [x] prepopulates the form inputs if the pokemon has those properties.
- [x] Add a 'submit' event to the modal form that:
  - [x] adds or updates properties in data.editing based on form user inputs.
  - [x] Replace the original object in the data.entries array for the edited entry with the new object with the edited data.
  - [x] Reset data.editing to null.
- [x] Add an event listener to the X button on the top right corner of the modal that changes the class of the view to 'hidden' and resets data.editing to null.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
