### ISSUE TITLE
Feature: User can delete a Pokemon

### ISSUE THREAD

**Issue by laykevin** [laykevin/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a Pokemon.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When a user clicks the 'RELEASE' button on the Pokemon editing modal, a confirmation modal will appear asking if they are sure they want to release that Pokemon. If confirmed, the users Pokemon will be released into the wild (deleted).

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121647421/222281523-f787e344-bac5-46a4-af1d-11b4149eb5b4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal to match the figma.
- [x] Add an event listener to the 'RELEASE' button in the editing modal that brings up the new modal when clicked.
- [x] Add an event listener to the 'cancel' button in the new modal that hides the new modal when clicked.
- [x] Add an event listener to the 'confirm' button that:
  - [x] Removes the corresponding Pokemon object from the data model's entries array.
  - [x] Removes the corresponding Pokemon's sprite from the DOM.
  - [x] Hides both the new modal and the editing modal.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
