### ISSUE TITLE
Feature: User can make a team of Pokemon

### ISSUE THREAD

**Issue by laykevin** [laykevin/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add Pokemon to their Party.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can withdraw Pokemon from their box to their Party, up to 6 Pokemon.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121647421/222298078-82db6e2a-c9a5-4158-97e8-05c9d38728ff.png)
![image](https://user-images.githubusercontent.com/121647421/222506079-734494fb-5fd6-42fd-af5f-4e6908f12e8a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a new function named viewSwap with a single parameter representing the name of the view to show (the value will be either ”box-view” or ”party-view”). This function should show the view whose name was provided as an argument, as well as assign the string argument to the data.view property so that the currently shown view is tracked in the data model for the application.
- [x] Wrap everything in between the 'Box 1' heading and the sprites div in another div with the id 'box-view'.
- [x] Create a new div with the id 'party-view' with another div inside to hold the `img`s of the pokemon in 'My Party'.
- [x] Create a new property in data model in data.js named 'partyEntries' with a value of an empty array.
- [x] Add some dummy artwork to the div and adjust size to match figma (1 img for mobile view, 3 for desktop view per row).
- [x] Create a `function` named `renderParty`.  The function should generate and return a DOM tree for a single entry that matches the entries you created in the new party-view div.
- [x] Add the `renderParty` function to the `DOMContentLoaded` event listener on the document object to render each entry in the `partyEntries` array. 
- [x] Add an event listener to the 'withdraw' button on the editing modal that does the following when clicked:
  - [x] calls the deletePokemon function
  - [x] Pushes data.editing into the new partyEntries array.
  - [x] calls the `renderParty` function with the argument data.editing and appends it to the div inside the party-view
- [x] Create a condition statement that does not allow more than 6 entries in the `partyEntries` array.
- [x] Remove dummy data
- [x] Add a 'deposit' button to the editing modal in between the 'release' button and the 'withdraw' button.
- [x] Add an event listener to the party-view that does the following when an img is clicked:
  - [x] Opens the editing modal
  - [x] Hides the 'withdraw' button and shows the 'deposit' button.
- [x] Update the showModal callback function to hide the 'deposit' button and show the 'withdraw' button when a spite in the box-view is clicked.
- [x] Add an event listener to the 'deposit' button in the editing modal that does the following when clicked:
  - [x] Removes the entry from the `partyEntries` array
  - [x] Removes the `img` from the party-entries view
  - [x] Pushes data.editing into the `entries` array
  - [x] Calls the `renderPokemon` function with argument data.editing and appends it to the box-view.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
